name: Build Storeman

on:
  push:
    tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+-sfos3.2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir RPMS

    - name: Build 3.2.1.20
      env:
        RELEASE: 3.2.1.20
        ARCHS: armv7hl i486
      run: bash ./scripts/gha-build.sh

    - name: Create release
      run: bash ./scripts/gha-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
